// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://burnsecmofxetfvqrvsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1cm5zZWNtb2Z4ZXRmdnFydnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNzM4NzMsImV4cCI6MjA2Njc0OTg3M30.HE9bUn40Wa2dDJsq2b0zSiP7Dz_3lBBywadvFXDWPqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);